In [1]:
# Numpy Array
import numpy as np
numbers = np.array([10,20,30,40])
print(numbers)

[10 20 30 40]


In [ ]:
# NumPy Array vs Python List (Same syntax but different behavior)

In [ ]:
# NumPy Array: Element-Wise Vectorized Operation
# In NumPy, numbers * 2 performs vectorized arithmetic (broadcasting).
# It applies scalar multiplication to every individual element inside the array.

In [2]:
numbers = np.array([10,20,30,40])
print(numbers * 2)

[20 40 60 80]


In [ ]:
# Python Standard List: Sequence Replication
# In standard Python, lists are generic containers, not mathematical vectors.
# The * operator on a sequence defines sequence repetition.
# It duplicates and concatenates the elements rather than modifying the values within.

In [3]:
numbers = [10,20,30,40]
print (numbers * 2) 

[10, 20, 30, 40, 10, 20, 30, 40]


In [ ]:
# 2-D Array (similar to a table or matrix)

In [4]:
arr = np.array([
    [10,20,30],
    [40,50,60]
])

print(arr)

[[10 20 30]
 [40 50 60]]


In [ ]:
# Creating Arrays using Built-in Methods

In [15]:
# Creates an array with zeros
arr = np.zeros(5)
print(arr)


# 2D Array
arr = np.zeros((2,3))
print(arr)


# Creates an array containing ones
arr = np.ones(5)
print(arr)


# Create an array filled with a specific value
arr = np.full(5,7)
print(arr)


# Range
arr = np.arange(1,10)
print(arr)


# Create evenly spaced numbers between two values (useful in plotting and calculations)
arr = np.linspace(0,10,5)
print(arr)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[7 7 7 7 7]
[1 2 3 4 5 6 7 8 9]
[ 0.   2.5  5.   7.5 10. ]


In [ ]:
# Creating Arrays using Random Numbers

In [18]:
# Random Array
arr = np.random.rand(5)  # -> Numpy = Package, random = library, rand = function
print(arr)


# Random Integers
arr = np.random.randint(1,100,5)
print(arr)


# Random 2D Array
arr = np.random.randint(1,10, size=(3,4))
print(arr)

[0.12678682 0.56402893 0.12263226 0.78448312 0.15021365]
[41 12 30 34 36]
[[6 6 9 4]
 [9 1 9 4]
 [1 7 3 7]]


In [ ]:
# NumPy Built-in Functions

In [ ]:
# Shape()
# Size()
# dtype
# reshape

In [ ]:
# NumPy Aggregation Methods

In [22]:
arr = np.array([10,50,20,80,30])
print(arr.max())
print(arr.min())

print(arr.argmax())  # returns index of the largest value

80
10
3


In [ ]:
# Logical selection of data (imp in ML).
# Selecting specific Rows or Columns
# Boolean Masking
