In [4]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [5]:
# Features

In [10]:
X = np.array([
    [1000,2,10],
    [1500,3,5],
    [2000,4,3],
    [2500,4,2],
    [3000,5,1]
])

y = np.array([200,300,400,500,600])

In [11]:
model = LinearRegression()

model.fit(X,y)

print("Intercept", model.intercept_)
print("Coefficients", model.coef_)

new_house = [[2200,4,4]]

prediction = model.predict(new_house)

print("Prediction Price:", prediction)

Intercept 1.1368683772161603e-13
Coefficients [2.00000000e-01 2.18277001e-15 6.55033969e-15]
Prediction Price: [440.]


In [18]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score
import numpy as np

In [19]:
X = np.array([
    [1000, 2, 10],
    [1200, 2, 8],
    [1500, 3, 5],
    [1700, 3, 4],
    [2000, 4, 3],
    [2200, 4, 3],
    [2500, 4, 2],
    [2800, 5, 2],
    [3000, 5, 1],
    [3500, 5, 1]
])


# Target variable array containing 10 elements
y = np.array([200, 240, 300, 340, 400, 440, 500, 560, 600, 700])


# Splits features (X) and targets (y) into train/test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.2, 
    random_state=42
)

# 1. Initialize the model
model = LinearRegression()

# 2. Train the model on the training data
model.fit(X_train, y_train)

# 3. Predict values using the test dataset
y_pred = model.predict(X_test)

# 4. Print prediction results alongside actual values
print("Predictions:", y_pred)
print("Actual:", y_test)

# 5. Calculate and display model performance metrics
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R^2:", r2_score(y_test, y_pred))

Predictions: [600. 240.]
Actual: [600 240]
MAE: 1.1368683772161603e-13
RMSE: 1.6077746776921858e-13
R^2: 1.0


In [ ]:
# Polynomial Regression

In [22]:
import numpy as np
from sklearn.linear_model import LinearRegression

X = np.array([
    [1],
    [2],
    [3],
    [4],
    [5],
    [6]
])

y = np.array([2,5,10,17,26,37])

linear_model = LinearRegression()
linear_model.fit(X,y)

print(linear_model.predict([[7]]))  # Linear Regression


# Polynomial Regression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

poly = PolynomialFeatures(degree=2)

X_poly = poly.fit_transform(X)
print(X_poly)

[40.66666667]
[[ 1.  1.  1.]
 [ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]
 [ 1.  5. 25.]
 [ 1.  6. 36.]]
